const svgNS='http://www.w3.org/2000/svg';
const chart=document.querySelector('#rotationChart');
const trailLayer=document.querySelector('#trailLayer');
const bubbleLayer=document.querySelector('#bubbleLayer');
const playBtn=document.querySelector('#playBtn');
const frameLabel=document.querySelector('#frameLabel');
const rangeBtns=[...document.querySelectorAll('[data-days]')];
let data=null,config=null,windowDays=10,selectedId='ABF',frameOffset=0,timer=null;

const xScale=v=>62+(Math.max(0,Math.min(100,v))/100)*646;
const yScale=v=>414-(Math.max(0,Math.min(100,v))/100)*380;
const quadrant=(x,y)=>x>=50&&y>=50?'領先區':x<50&&y>=50?'改善區':x<50&&y<50?'落後區':'弱化區';
const currentIndex=()=>data.sectors[0].path.length-1-frameOffset;
const startIndex=()=>Math.max(0,currentIndex()-windowDays+1);
const sectorMeta=id=>config.sectors.find(s=>s.id===id)||{};
function svgEl(tag,attrs={}){const el=document.createElementNS(svgNS,tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,String(v)));return el}
function movement(s){const end=currentIndex(),start=Math.max(0,end-windowDays+1),a=s.path[start],b=s.path[end];return{dx:b[0]-a[0],dy:b[1]-a[1],score:b[0]-a[0]+b[1]-a[1],startQ:quadrant(a[0],a[1]),endQ:quadrant(b[0],b[1])}}
function renderChart(){trailLayer.innerHTML='';bubbleLayer.innerHTML='';const end=currentIndex(),start=startIndex();data.sectors.forEach(s=>{const pts=s.path.slice(start,end+1);if(!pts.length)return;const selected=s.id===selectedId;trailLayer.appendChild(svgEl('polyline',{points:pts.map(p=>`${xScale(p[0])},${yScale(p[1])}`).join(' '),fill:'none',stroke:selected?'#3559e0':'#64748b','stroke-width':selected?3:1.5,opacity:selected?.95:.42,'stroke-linecap':'round','stroke-linejoin':'round'}));pts.slice(0,-1).forEach((p,i)=>trailLayer.appendChild(svgEl('circle',{cx:xScale(p[0]),cy:yScale(p[1]),r:Math.max(2.2,5-(pts.length-1-i)*.18),fill:'#fff',stroke:selected?'#3559e0':'#94a3b8','stroke-width':1,opacity:Math.max(.18,.75-(pts.length-1-i)*.04)})));const p=pts[pts.length-1],g=svgEl('g',{tabindex:'0',role:'button','aria-label':`${s.label} ${quadrant(p[0],p[1])}`}),r=8+Math.max(0,s.heat-.8)*11,b=svgEl('circle',{cx:xScale(p[0]),cy:yScale(p[1]),r,fill:selected?'#3559e0':'#111827',stroke:'#fff','stroke-width':selected?3:2}),label=svgEl('text',{x:xScale(p[0]),y:yScale(p[1])-r-7,'text-anchor':'middle','font-size':selected?12:11,'font-weight':700,fill:'#172033'});label.textContent=s.label;g.style.cursor='pointer';g.append(b,label);g.addEventListener('click',()=>{selectedId=s.id;renderAll()});g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectedId=s.id;renderAll()}});bubbleLayer.appendChild(g)});frameLabel.textContent=frameOffset===0?`顯示最近 ${windowDays} 個交易日`:`動畫回看：${frameOffset} 日前`}
function renderDetail(){const s=data.sectors.find(x=>x.id===selectedId)||data.sectors[0],m=movement(s),p=s.path[currentIndex()],meta=sectorMeta(s.id);document.querySelector('#detailTitle').textContent=meta.name||s.label;document.querySelector('#detailTier').textContent=`${meta.tier||''} · ${(meta.theme||[]).join(' / ')}`;document.querySelector('#detailQuadrant').textContent=quadrant(p[0],p[1]);document.querySelector('#detailDirection').textContent=m.dx>0&&m.dy>0?'↗↗':m.dy<0?'↘':'→';document.querySelector('#detailHeat').textContent=`${s.heat.toFixed(2)}×`;document.querySelector('#detailBreadth').textContent=`${s.breadth}%`;document.querySelector('#detailCatalyst').textContent=meta.catalyst||'—';document.querySelector('#stockList').innerHTML=s.stocks.map(st=>`<div class="stock-row"><div><strong>${st.name}</strong><small>${st.ticker} · ${st.role}</small></div><span class="state">${st.state}</span></div>`).join('')}
function rankRow(o,up){return `<button class="rank-row" data-rank="${o.s.id}"><span>${up?'↗':'↘'}</span><span><strong>${sectorMeta(o.s.id).name||o.s.label}</strong><small>${o.m.startQ} → ${o.m.endQ}</small></span><em>Δ ${o.m.dx>=0?'+':''}${o.m.dx.toFixed(0)} / ${o.m.dy>=0?'+':''}${o.m.dy.toFixed(0)}</em></button>`}
function renderRankings(){const all=data.sectors.map(s=>({s,m:movement(s)}));const up=all.filter(o=>o.m.dx>0&&o.m.dy>0).sort((a,b)=>b.m.score-a.m.score).slice(0,5),down=all.filter(o=>o.m.dx<0||o.m.dy<0).sort((a,b)=>(a.m.dx+a.m.dy)-(b.m.dx+b.m.dy)).slice(0,5);document.querySelector('#upDays').textContent=windowDays;document.querySelector('#downDays').textContent=windowDays;document.querySelector('#upRanking').innerHTML=up.map(o=>rankRow(o,true)).join('')||'<p>目前沒有一致往右上的族群</p>';document.querySelector('#downRanking').innerHTML=down.map(o=>rankRow(o,false)).join('')||'<p>目前沒有明顯弱化族群</p>';document.querySelectorAll('[data-rank]').forEach(btn=>btn.addEventListener('click',()=>{selectedId=btn.dataset.rank;renderAll()}))}
function renderAll(){renderChart();renderDetail();renderRankings()}
function stopPlayback(){if(timer){clearInterval(timer);timer=null}playBtn.textContent='▶ 播放'}
function startPlayback(){stopPlayback();frameOffset=windowDays-1;playBtn.textContent='Ⅱ 暫停';renderAll();timer=setInterval(()=>{frameOffset-=1;if(frameOffset<=0){frameOffset=0;stopPlayback()}renderAll()},650)}
function setDays(days){windowDays=Math.max(5,Math.min(20,Number(days)||10));frameOffset=0;rangeBtns.forEach(b=>b.classList.toggle('active',Number(b.dataset.days)===windowDays));stopPlayback();renderAll()}
rangeBtns.forEach(btn=>btn.addEventListener('click',()=>setDays(btn.dataset.days)));playBtn.addEventListener('click',()=>timer?stopPlayback():startPlayback());
Promise.all([fetch('./data/latest/rotation.json').then(r=>r.json()),fetch('./config/sectors.json').then(r=>r.json())]).then(([rotation,sectors])=>{data=rotation;config=sectors;selectedId=data.sectors[0]?.id||'ABF';document.querySelector('#dataStatus').textContent=`資料日期 ${data.updated_at} · ${data.source==='mock'?'Prototype 假資料':'正式資料'}`;setDays(data.window_default||10)}).catch(err=>{console.error(err);document.querySelector('#dataStatus').textContent='資料載入失敗，請重新整理頁面。'});
